# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# zsh theme -------------------------------------------------------------------
# Set the name of the theme to load (~/.oh-my-zsh/themes/*)
# Addresses https://github.com/denysdovhan/spaceship-zsh-theme/issues/228
SPACESHIP_KUBECONTEXT_SHOW="${SPACESHIP_KUBECONTEXT_SHOW:=false}"
ZSH_THEME="spaceship"

# zsh plugins -----------------------------------------------------------------
# Which plugins would you like to load? (~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(docker git pip python)

# get this party started ------------------------------------------------------
source $ZSH/oh-my-zsh.sh

# spaceship theme settings ----------------------------------------------------
source $HOME/my/dotfiles/zsh/spaceship-config

# zsh options -----------------------------------------------------------------
setopt autolist
setopt correct
unsetopt cdablevars # this REALLY slowed down oh-my-zsh for me

# exports ---------------------------------------------------------------------
source $HOME/my/dotfiles/zsh/exports

# private exports -------------------------------------------------------------
PRIVATE_ZSH_FILE=$HOME/my/dotfiles/zsh/private
[ -f $PRIVATE_ZSH_FILE ] && source $PRIVATE_ZSH_FILE

# aliases ---------------------------------------------------------------------
source $HOME/my/dotfiles/zsh/aliases

# tmuxifier -------------------------------------------------------------------
if which tmuxifier > /dev/null; then eval "$(tmuxifier init -)"; fi

# nodenv ----------------------------------------------------------------------
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi

# autoenv ---------------------------------------------------------------------
AUTOENV_FILE=`brew --prefix`/opt/autoenv/activate.sh
[ -f $AUTOENV_FILE ] && source $AUTOENV_FILE

# virtualenvwrapper  ----------------------------------------------------------
VIRTUALENVWRAPPER_FILE=/usr/local/bin/virtualenvwrapper.sh
[ -f $VIRTUALENVWRAPPER_FILE ] && source $VIRTUALENVWRAPPER_FILE

# pyenv -----------------------------------------------------------------------
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# added by travis gem
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# The next line updates PATH for the Google Cloud SDK.
if [ -f $HOME/Downloads/google-cloud-sdk/path.zsh.inc ]; then
  source '$HOME/Downloads/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f $HOME/Downloads/google-cloud-sdk/completion.zsh.inc ]; then
  source '$HOME/Downloads/google-cloud-sdk/completion.zsh.inc'
fi

# oh hai hamurai --------------------------------------------------------------
[ -f /opt/hamurai/env.sh ] && source /opt/hamurai/env.sh

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/rleland/.nodenv/versions/6.11.4/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/rleland/.nodenv/versions/6.11.4/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/rleland/.nodenv/versions/6.11.4/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/rleland/.nodenv/versions/6.11.4/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh