# boxen -----------------------------------------------------------------------
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# zsh theme -------------------------------------------------------------------
# Set the name of the theme to load (~/.oh-my-zsh/themes/*)
ZSH_THEME="spaceship"

# zsh plugins -----------------------------------------------------------------
# Which plugins would you like to load? (~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(brew docker git git-flow mercurial pip python)

# get this party started ------------------------------------------------------
source $ZSH/oh-my-zsh.sh

# spaceship theme settings ----------------------------------------------------
source $HOME/my/dotfiles/zsh/spaceship-config

# zsh options -----------------------------------------------------------------
setopt autolist
setopt correct
unsetopt cdablevars # this REALLY slowed down oh-my-zsh for me

# exports ---------------------------------------------------------------------
source $HOME/my/dotfiles/zsh/exports

# private exports -------------------------------------------------------------
PRIVATE_EXPORTS_FILE=$HOME/my/dotfiles/zsh/private
[ -f $PRIVATE_EXPORTS_FILE ] && source $PRIVATE_EXPORTS_FILE

# aliases ---------------------------------------------------------------------
source $HOME/my/dotfiles/zsh/aliases

# tmuxifier -------------------------------------------------------------------
eval "$(tmuxifier init -)"

# autoenv ---------------------------------------------------------------------
AUTOENV_FILE=`brew --prefix`/opt/autoenv/activate.sh
[ -f $AUTOENV_FILE ] && source $AUTOENV_FILE

# virtualenvwrapper -----------------------------------------------------------
VIRTUALENVWRAPPER_FILE=`brew --prefix`/bin/virtualenvwrapper.sh
[ -f $VIRTUALENVWRAPPER_FILE ] && source $VIRTUALENVWRAPPER_FILE

# pyenv -----------------------------------------------------------------------
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

# added by travis gem
[ -f /Users/rleland/.travis/travis.sh ] && source /Users/rleland/.travis/travis.sh

PATH="/Users/rleland/perl5/bin${PATH+:}${PATH}"; export PATH;
PERL5LIB="/Users/rleland/perl5/lib/perl5${PERL5LIB+:}${PERL5LIB}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/Users/rleland/perl5${PERL_LOCAL_LIB_ROOT+:}${PERL_LOCAL_LIB_ROOT}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/Users/rleland/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/rleland/perl5"; export PERL_MM_OPT;

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/rleland/Downloads/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/rleland/Downloads/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/rleland/Downloads/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/rleland/Downloads/google-cloud-sdk/completion.zsh.inc'
fi


source "/Users/rleland/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
