# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# zsh theme -------------------------------------------------------------------
# Set the name of the theme to load (~/.oh-my-zsh/themes/*)
ZSH_THEME="richleland"

# zsh plugins -----------------------------------------------------------------
# Which plugins would you like to load? (~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(brew git git-flow jira knife mercurial pip python)

# get this party started ------------------------------------------------------
source $ZSH/oh-my-zsh.sh

# zsh options -----------------------------------------------------------------
setopt autolist
setopt correct
unsetopt cdablevars # this REALLY slowed down oh-my-zsh for me

# exports ---------------------------------------------------------------------
source $HOME/my/dotfiles/zsh/exports

# aliases ---------------------------------------------------------------------
source $HOME/my/dotfiles/zsh/aliases

# tmuxifier -------------------------------------------------------------------
eval "$(tmuxifier init -)"

# autoenv ---------------------------------------------------------------------
AUTOENV_FILE=`brew --prefix`/opt/autoenv/activate.sh
[ -f $AUTOENV_FILE ] && source $AUTOENV_FILE

# virtualenvwrapper -----------------------------------------------------------
VIRTUALENVWRAPPER_FILE=/usr/local/bin/virtualenvwrapper.sh
[ -f $VIRTUALENVWRAPPER_FILE ] && source $VIRTUALENVWRAPPER_FILE
